### ISSUE TITLE
تحسين عرض الصور وتصميم الموقع

### ISSUE THREAD

**Issue by astropandon** [astropandon/php#1]
### 1. تحسينات عرض الصور:
- إنشاء نظام معاينة الصور (Image Preview)
- تحسين تنسيق وحجم الصور
- إضافة خاصية تكبير الصور عند النقر عليها
- التحقق من وجود الصور قبل عرضها
- إضافة صورة افتراضية في حال عدم وجود صورة للمنتج

### 2. تحسينات التصميم:
- إضافة تأثيرات حركية (Hover Effects)
- تحسين تباعد العناصر
- إضافة ظلال وحدود للصور
- تحسين تجاوب الموقع مع مختلف الشاشات

### التنفيذ المقترح:

1. تعديل ملف `index.php`:
```php
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    <?php foreach ($products as $product): ?>
    <div class="bg-white rounded-lg shadow-lg overflow-hidden transform transition duration-300 hover:scale-105">
        <div class="relative h-64">
            <?php
            $imagePath = 'uploads/' . htmlspecialchars($product['image']);
            $imageUrl = file_exists($imagePath) ? $imagePath : 'images/default-product.jpg';
            ?>
            <img src="<?php echo $imageUrl; ?>" 
                 alt="<?php echo htmlspecialchars($product['libPdt']); ?>" 
                 class="w-full h-full object-cover cursor-pointer"
                 onclick="openImageModal(this.src)"
                 loading="lazy">
        </div>
        <!-- باقي محتوى البطاقة -->
    </div>
    <?php endforeach; ?>
</div>

<!-- Modal للصور -->
<div id="imageModal" class="fixed inset-0 bg-black bg-opacity-75 hidden items-center justify-center z-50">
    <div class="relative">
        <img id="modalImage" src="" alt="" class="max-w-[90vw] max-h-[90vh] object-contain">
        <button onclick="closeImageModal()" class="absolute top-4 right-4 text-white text-xl">&times;</button>
    </div>
</div>
```

2. إضافة JavaScript للتعامل مع الصور:
```javascript
function openImageModal(src) {
    const modal = document.getElementById('imageModal');
    const modalImg = document.getElementById('modalImage');
    modal.classList.remove('hidden');
    modal.classList.add('flex');
    modalImg.src = src;
}

function closeImageModal() {
    const modal = document.getElementById('imageModal');
    modal.classList.add('hidden');
    modal.classList.remove('flex');
}

// إغلاق Modal عند النقر خارج الصورة
document.getElementById('imageModal').addEventListener('click', function(e) {
    if (e.target === this) {
        closeImageModal();
    }
});
```

3. تحسينات CSS إضافية:
```css
.product-card {
    transition: transform 0.3s ease-in-out;
}

.product-card:hover {
    transform: translateY(-5px);
}

.image-container {
    position: relative;
    overflow: hidden;
    border-radius: 8px 8px 0 0;
}

.image-container img {
    transition: transform 0.3s ease-in-out;
}

.image-container:hover img {
    transform: scale(1.1);
}
```

4. إنشاء مجلد للصور الافتراضية:
```
e/
├── images/
│   └── default-product.jpg
└── uploads/
```

### الخطوات التالية:
1. إنشاء مجلد `images` وإضافة صورة افتراضية
2. تنفيذ التعديلات المقترحة في الملفات
3. اختبار عرض الصور في مختلف أحجام الشاشات
4. التأكد من أداء تحميل الصور

### النتائج المتوقعة:
- تحسين تجربة المستخدم عند عرض الصور
- تصميم أكثر جاذبية وحداثة
- تحسين سرعة تحميل الصفحة
- تجربة مستخدم أفضل على الأجهزة المحمولة
